useHelm3: true
allowNamespaceDiscovery: true
ingress:
  enabled: true
  tls: true
  certManager:
    clusterIssuer: letsencrypt-prod
  annotations:
    kubernetes.io/ingress.class: contour
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/tls-acme: "true"
apprepository:
  initialRepos:
    - name: tac-repo
      url: https://charts.trials.tac.bitnami.com/demo
