service:
  type: Ingress
  tls:
    enabled: true
    existingSecret: harbor-tls-prod
    # notaryExistingSecret: notary-tls-prod

ingress:
  enabled: true
  certManager: true
  annotations:
    kubernetes.io/ingress.class: contour
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"

persistence:
  imageChartStorage:
    type: azure
